insert into empleados (nombre, apellido1, apellido2, dni, domicilio)values('Jesús', 'Martin', 'Batista', '11676189D', 'Calle Gondola Nº4')
insert into empleados (nombre, apellido1, apellido2, dni, domicilio)values('Manuel', 'Perez', 'Monagas', '45187663T', 'Calle Amapola Nº6')
insert into empleados (nombre, apellido1, apellido2, dni, domicilio)values('María', 'Serrano', 'Montesdeoca', '20202873H', 'Calle Tomas Morales Nº45')
insert into empleados (nombre, apellido1, apellido2, dni, domicilio)values('Patricia', 'Villanueva', 'León', '57471386K', 'Calle Venezuela Nº23')
insert into empleados (nombre, apellido1, apellido2, dni, domicilio)values('Javier', 'Leal', 'Poderoso', '20822321F', 'Calle Murga Nº11')